version: '2'
services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile
    image: webpack
    container_name: webpack-container
    ports:
      - "35729:35729"
    volumes:
      - .:/app
      - /app/node_modules